version: "3"

services:
  # MongoDB services
  momongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #  Node Api Service
  api:
    build: .
    restart: always
    ports:
      - 1150:1150
    environment:
      PORT: 1150
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: Pattarayut
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
